name: Continuos Integration, PHP Unit test

on: 
  pull_request: 
    branches: [develop]

jobs:
  ci-test-develop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1 # or alternative dependency management
    - uses: php-actions/phpunit@v9